# Generated by Django 4.0.4 on 2022-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('image_url', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('typeId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
